version: '3.3'
services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=marketplace
      - MYSQL_USER=marketplace
      - MYSQL_PASSWORD=marketplace
    networks:
      - net-backend
    ports:
      - 3306:3306
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    volumes:
    - esdata1:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
    - cluster.name=elasticsearch
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
    - net-backend
    ports:
    - 9200:9200
    - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    depends_on:
    - es
    environment:
      ELASTICSEARCH_URL: http://es:9200
    networks:
    - net-backend
    ports:
    - 5601:5601
  marketplace-backend:
    build: .
    depends_on:
      - db
      - es
    networks:
      - net-backend
      - net-frontend
    ports:
      - 9000:9000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_SCHEMA=marketplace
      - DATABASE_USER=marketplace
      - DATABASE_PASSWORD=marketplace
      - ELASTICSEARCH_HOST=es
      - ELASTICSEARCH_CLUSTER=elasticsearch
      - ELASTICSEARCH_PORT=9300
      - MY_SERVER_HOST=marketplace-backend
networks:
  net-backend:
  net-frontend:
volumes:
  db_data:
  esdata1:
    

