version: '3.3'
services:
  db:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=marketplace      
      - MYSQL_USER=marketplace
      - MYSQL_PASSWORD=marketplace
    networks:
      - net-backend
    ports:
      - 3306:3306
  marketplace-backend:
    image: viniciusfsouza/marketplace-backend:latest
    depends_on:
      - db
    networks:
      - net-backend
    ports:
      - 9000:9000
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=marketplace
      - DATABASE_NAME=marketplace
      - DATABASE_PORT=3306
networks:
  net-backend:
volumes:
  db_data:
    

